matchBlocks=alotofinterior:table_bamboo_dark_oak
method=ctm
faces=top
connect=block
innerSeams=false
tiles=<default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default>
