matchBlocks=alotofinterior:table_warped_acacia
method=ctm
faces=top
connect=block
innerSeams=false
tiles=<default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default>
