matchBlocks=alotofinterior:table_spruce_birch
method=ctm
faces=top
connect=block
innerSeams=false
tiles=<default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default>
