matchBlocks=alotofinterior:table_warped_cherry
method=ctm
faces=top
connect=block
innerSeams=false
tiles=<default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default>
