matchBlocks=alotofinterior:table_bamboo_birch
method=ctm
faces=top
connect=block
innerSeams=false
tiles=<default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default> <default>
